In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/soora/Desktop/project/self-coded/orders.csv")

In [3]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [4]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [5]:
df.columns = df.columns.str.replace(" ","_")

In [6]:
df['Ship_Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [7]:
import numpy as np
df['Ship_Mode'] = df['Ship_Mode'].replace(['Not Available','unknown'], np.nan)

In [8]:
df['Ship_Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [9]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [10]:
pd.to_datetime(df['Order_Date'], format = '%Y-%m-%d', errors='coerce')

0      2023-03-01
1      2023-08-15
2      2023-01-10
3      2022-06-18
4      2022-07-13
          ...
9989   2023-02-18
9990   2023-03-17
9991   2022-08-07
9992   2022-11-19
9993   2022-07-17
Name: Order_Date, Length: 9994, dtype: datetime64[ns]

In [11]:
#calculating the total sales 
df['discount'] = df['Discount_Percent']/100 * df['List_Price']

In [12]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [13]:
df['sales_price'] = df['List_Price'] - df['discount']

In [14]:
df.columns.str.lower()

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent', 'discount', 'sales_price'],
      dtype='object')

In [15]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0

In [16]:
df['profit'] = df['sales_price'] - df['cost_price']

In [17]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [18]:
df['revenue'] = df['Quantity'] * df['sales_price']

In [19]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_price,profit,revenue
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0,38.0

In [20]:
df.columns = df.columns.str.lower()

In [21]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sales_price,profit,revenue
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0,38.0

In [22]:
df.to_csv('name',index=False)

In [23]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sales_price,profit,revenue
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0,38.0

In [25]:
!pip install sqlalchamy


from sqlalchemy import create_engine

ERROR: Could not find a version that satisfies the requirement sqlalchamy (from versions: none)
ERROR: No matching distribution found for sqlalchamy

In [28]:
HOST = 'localhost'
USERNAME = 'root'
PASSWORD= 'Behumble12$$'
PORT='3306'
DATABASE='my_database'
DATABASE_URL = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}'
engine = create_engine(DATABASE_URL, echo=True)

In [30]:
table_name = 'orders'
df.to_sql(table_name, con=engine, if_exists='replace', index=False)

2025-02-15 22:53:49,879 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2025-02-15 22:53:49,880 INFO sqlalchemy.engine.Engine [raw sql] {}

2025-02-15 22:53:49,882 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-02-15 22:53:49,883 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-15 22:53:49,886 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-02-15 22:53:49,886 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-15 22:53:49,888 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-02-15 22:53:49,893 INFO sqlalchemy.engine.Engine DESCRIBE `my_database`.`orders`
2025-02-15 22:53:49,894 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-15 22:53:49,911 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	order_id BIGINT,
	order_date TEXT,
	ship_mode TEXT,
	segment TEXT,
	country TEXT,
	city TEXT,
	state TEXT,
	postal_code BIGINT,
	region TEXT,
	category TEXT,
	sub_category TEXT,
	product_id TEXT,
	cost_price BIGINT,
	list_price BIGINT,
	quantity BIGINT,
	discount_percent BIGINT,
	discount FLOAT(53),
	sales_price FLOAT(53),
	profit FLOAT(53),
	revenue FLOAT(53)
)


2025-02-15 22:53:49,912 INFO sqlalchemy.engine.Engine [no key 0.00114s] {}
2025-02-15 22:53:50,114 INFO sqlalchemy.engine.Engine INSERT INTO orders (order_id, order_date, ship_mode, segment, country, city, state, postal_code, region, category, sub_category, product_id, cost_price, list_price, quantity, discount_percent, discount, sales_price, profit, revenue) VALUES (%(order_id)s, %(order_date)s, %(ship_mode)s, %(segment)s, %(country)s, %(city)s, %(state)s, %(postal_code)s, %(region)s, %(category)s, %(sub_category)s, %(product_id)s, %(cost_price)s, %(list_price)s, %(quantity)s, %(discount_percent)s, %(discount)s, %(sales_price)s, %(profit)s, %(revenue)s)
2025-02-15 22:53:50,115 INFO sqlalchemy.engine.Engine [generated in 0.13882s] [{'order_id': 1, 'order_date': '2023-03-01', 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Bookcases', 'product_id': 'FUR-BO-10001798', 'cost_price': 240, 'list_price': 260, 'quantity': 2, 'discount_percent': 2, 'discount': 5.2, 'sales_price': 254.8, 'profit': 14.800000000000011, 'revenue': 509.6}, {'order_id': 2, 'order_date': '2023-08-15', 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Chairs', 'product_id': 'FUR-CH-10000454', 'cost_price': 600, 'list_price': 730, 'quantity': 3, 'discount_percent': 3, 'discount': 21.9, 'sales_price': 708.1, 'profit': 108.10000000000002, 'revenue': 2124.3}, {'order_id': 3, 'order_date': '2023-01-10', 'ship_mode': 'Second Class', 'segment': 'Corporate', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90036, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Labels', 'product_id': 'OFF-LA-10000240', 'cost_price': 10, 'list_price': 10, 'quantity': 2, 'discount_percent': 5, 'discount': 0.5, 'sales_price': 9.5, 'profit': -0.5, 'revenue': 19.0}, {'order_id': 4, 'order_date': '2022-06-18', 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Tables', 'product_id': 'FUR-TA-10000577', 'cost_price': 780, 'list_price': 960, 'quantity': 5, 'discount_percent': 2, 'discount': 19.2, 'sales_price': 940.8, 'profit': 160.79999999999995, 'revenue': 4704.0}, {'order_id': 5, 'order_date': '2022-07-13', 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Office Supplies', 'sub_category': 'Storage', 'product_id': 'OFF-ST-10000760', 'cost_price': 20, 'list_price': 20, 'quantity': 2, 'discount_percent': 5, 'discount': 1.0, 'sales_price': 19.0, 'profit': -1.0, 'revenue': 38.0}, {'order_id': 6, 'order_date': '2022-03-13', 'ship_mode': None, 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Furniture', 'sub_category': 'Furnishings', 'product_id': 'FUR-FU-10001487', 'cost_price': 50, 'list_price': 50, 'quantity': 7, 'discount_percent': 3, 'discount': 1.5, 'sales_price': 48.5, 'profit': -1.5, 'revenue': 339.5}, {'order_id': 7, 'order_date': '2022-12-28', 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Art', 'product_id': 'OFF-AR-10002833', 'cost_price': 10, 'list_price': 10, 'quantity': 4, 'discount_percent': 3, 'discount': 0.3, 'sales_price': 9.7, 'profit': -0.3000000000000007, 'revenue': 38.8}, {'order_id': 8, 'order_date': '2022-01-25', 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Technology', 'sub_category': 'Phones', 'product_id': 'TEC-PH-10002275', 'cost_price': 860, 'list_price': 910, 'quantity': 6, 'discount_percent': 5, 'discount': 45.5, 'sales_price': 864.5, 'profit': 4.5, 'revenue': 5187.0}  ... displaying 10 of 9994 total bound parameter sets ...  {'order_id': 9993, 'order_date': '2022-11-19', 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Costa Mesa', 'state': 'California', 'postal_code': 92627, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Paper', 'product_id': 'OFF-PA-10004041', 'cost_price': 30, 'list_price': 30, 'quantity': 4, 'discount_percent': 3, 'discount': 0.8999999999999999, 'sales_price': 29.1, 'profit': -0.8999999999999986, 'revenue': 116.4}, {'order_id': 9994, 'order_date': '2022-07-17', 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Westminster', 'state': 'California', 'postal_code': 92683, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Appliances', 'product_id': 'OFF-AP-10002684', 'cost_price': 210, 'list_price': 240, 'quantity': 2, 'discount_percent': 3, 'discount': 7.199999999999999, 'sales_price': 232.8, 'profit': 22.80000000000001, 'revenue': 465.6}]
2025-02-15 22:53:50,692 INFO sqlalchemy.engine.Engine COMMIT

9994